version: '3.8'

services:
  postgresql:
    image: postgres:15.15-alpine3.22
    restart: always
    ports:
      - '${POSTGRES_FORWARD_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  
  golang:
    build:
     context: .
    restart: always
    ports:
     - '${APP_PORT:-3000}:3000'
    depends_on:
      - postgresql